pipeline {
    agent {
        label 'docker-test'
    }
    environment {
        DOCKER_HOST_IP = '172.26.87.236'
        UE1_IMEI = '356938035643803'
        UE1_IMEISV = '4370816125816151'
        UE1_IMSI = '001011234567895'
        UE1_KI = '8baf473f2f8fd09487cccbd7097c6862'
        UE1_OP = '11111111111111111111111111111111'
        UE1_AMF = '8000'
    }

    stages {
        stage('Debug') {
            steps {
                sh '''
            docker ps
        '''
            }
        }
        stage('Github Checkout') {
            steps {
                git 'https://github.com/herlesupreeth/docker_open5gs.git'
            }
        }
        stage('Docker Build docker_open5gs') {
            steps {
                dir('base') {
                    sh ''' if ! docker image inspect docker_open5gs:latest >/dev/null 2>&1; then
                            docker build -t docker_open5gs:latest .
                        fi'''
                }
            }
        }
            stage('Docker Build docker_srslte') {
            steps {
                dir('srslte') {
                    sh ''' if ! docker image inspect docker_srslte:latest >/dev/null 2>&1; then
                            docker build -t docker_srslte:latest .
                        fi'''
                }
            }
            }

        stage('Docker Build docker_srsran') {
            steps {
                dir('srsran') {
                    sh ''' if ! docker image inspect docker_srsran:latest >/dev/null 2>&1; then
                            docker build -t docker_srsran:latest .
                        fi'''
                }
            }
        }
        stage('Set env variables') {
            steps {
                sh '''
                    set -a
                    sed -i 's/^DOCKER_HOST_IP=.*/DOCKER_HOST_IP=172.26.87.236/' .env
                    . ./.env
                    set +a
                '''
            }
        }
        stage('Run 5G Core') {
            steps {
                sh '''
                    set -a
                    . ./.env
                    set +a
                    docker compose -f sa-deploy.yaml up -d metrics
                    docker exec -it metrics ls -la /mnt/metrics
                '''
            }
        }
    }
}
