pipeline {
    agent {
        label 'docker-test'
    }
    environment {
        DOCKER_HOST_IP = '172.26.87.236'
        UE1_IMEI = '356938035643803'
        UE1_IMEISV = '4370816125816151'
        UE1_IMSI = '001011234567895'
        UE1_KI = '8baf473f2f8fd09487cccbd7097c6862'
        UE1_OP = '11111111111111111111111111111111'
        UE1_AMF = '8000'
    }

    stages {
        stage('Debug') {
            steps {
                sh '''
            docker ps
        '''
            }
        }
        stage('Github Checkout') {
            steps {
                git 'https://github.com/herlesupreeth/docker_open5gs.git'
            }
        }
    }
}
